baseURL = "https://ansuman-satapathy.github.io/"
languageCode = "en-us"
title = "Ansuman"
theme = "hello-friend-ng"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  defaultTheme    = "dark" 
  enableThemeToggle = true
  showReadTime    = true

  # --- LANDING PAGE SETTINGS ---
  [params.home]
    introHeight = "fullheight"
    showLatest = false
    
  [params.home.profile]
    enable = true
    title = "Ansuman"
    subtitle = "Backend âžœ DevOps | Python | Go"    
    # image = "img/avatar.jpg" 

    # Your Social Links on the Landing Page
    [[params.home.profile.social]]
      icon = "github"
      url = "https://github.com/ansuman-satapathy"
    [[params.home.profile.social]]
      icon = "linkedin"
      url = "https://linkedin.com/in/ansuman-satapathy"
    [[params.home.profile.social]]
      icon = "mail"
      url = "mailto:satapathyansuman12@gmail.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Logs"
    url        = "/posts/"